ACTIVE_PROFILE: dev

POSTGRES_USERNAME: user
POSTGRES_PASSWORD: letMeinMomo
POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
POSTGRES_DATABASE: localdb

USER_NAME: admin
PASSWORD: letMeinMomo
ROLES: EUREKA_CLIENT

SERVER_PORT: 5002
UI_APP_URL: http://localhost:3000

