ACTIVE_PROFILE: prod

POSTGRES_USERNAME: user
POSTGRES_PASSWORD: letMeinMomo
POSTGRES_HOST: 192.168.1.209
POSTGRES_PORT: 5432
POSTGRES_DATABASE: localdb

USER_NAME: admin
PASSWORD: letMeinMomo
ROLES: EUREKA_CLIENT

SERVER_PORT: 5002
UI_APP_URL: http://localhost:3000